### ISSUE TITLE
[FEATURE] 이미지 로더 구현하기

### ISSUE THREAD

**Issue by aurora32s** [aurora32s/RandomPhoto#7]
### 📌 내용
이미지 URL을 가지고 서버로부터 이미지를 받아오는 로직 구현하기

### 🛠 ToDo
- [x] URL을 가지고 서버로부터 이미지 bitmap 받아오기
- [x] 이미지 로딩 처리
- [x] 이미지 로드 성공 처리
- [x] 이미지 로드 실패 처리
- [x] 받아온 이미지를 Image로 화면에 보여주기

### 🍿 조건
MainActivity에서 Image Component 두고 테스트하기
